spring.jpa.hibernate.ddl-auto: update
spring.datasource.url: jdbc:hsqldb:file:addon-db # Use a file-based backing store for HSQL
#spring.jpa.database=POSTGRESQL
#spring.datasource.platform=postgres
#spring.datasource.url=jdbc:postgresql://yourhost:5432/databaseName?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
#spring.datasource.username=""
#spring.datasource.password=""
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.testWhileIdle=true
#spring.datasource.validationQuery=SELECT 1
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

addon:
  key: atlassian-connect-spring-boot-sample-atlaskit
  base-url: http://localhost:${local.server.port}

logging.level.com.atlassian.connect.spring: DEBUG
